In [59]:
from pandas import *
import matplotlib.pyplot as plt
%matplotlib inline

In [60]:
Timestamp('2012-05-01')

Timestamp('2012-05-01 00:00:00')

In [74]:

dates = pd.date_range('1984', periods=20, freq='2A')

dates = [Timestamp('1984-12-31'), Timestamp('1989-12-31'), Timestamp('1994-12-31'), Timestamp('1999-12-31')
        , Timestamp('2001-12-31'), Timestamp('2003-12-31'), Timestamp('2005-12-31'), Timestamp('2007-12-31')
        , Timestamp('2009-12-31'), Timestamp('2011-12-31'), Timestamp('2013-12-31')]

data = pd.read_csv('a_all.txt', '\t')
#data
df = pd.DataFrame(data, columns=['impWealthWE84', 'impWealthWE89', 'impWealthWE94', 'impWealthWE99',
                                              'impWealthWE01', 'impWealthWE03', 'impWealthWE05', 'impWealthWE07',
                                               'impWealthWE09', 'impWealthWE11', 'impWealthWE13'], index=dates )
df

,impWealthWE84,impWealthWE89,impWealthWE94,impWealthWE99,impWealthWE01,impWealthWE03,impWealthWE05,impWealthWE07,impWealthWE09,impWealthWE11,impWealthWE13
1984-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1989-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
ts = pd.Series(data, index=dates, columns=['impWealthWE84', 'impWealthWE89', 'impWealthWE94', 'impWealthWE99',
                                              'impWealthWE01', 'impWealthWE03', 'impWealthWE05', 'impWealthWE07',
                                               'impWealthWE09', 'impWealthWE11', 'impWealthWE13'])
ts.plot()

TypeError: __init__() got an unexpected keyword argument 'columns'